### ISSUE TITLE
Implementar formulário para busca de desaparecidos

### ISSUE THREAD

**Issue by magnonasc** [UNIRIO-Voluntarios/desaparecidos-rj-mobile#1]
O esqueleto do formulário já se encontra no aplicativo, sendo necessário ainda trabalho para tornar os tipos de entradas compatíveis com o esperado para que se possa tratá-las da forma correta antes de enviá-las para o WebService criado por @RafaelStavale.

**Comment by thaisssimoes** [comment]
Resolvido
